export * from './IUser';
export * from './IList';
export * from './IMapper';
export * from './IProduct';
export * from './IRepository';
export * from './IUseCase';
export * from './IScrapper';
export * from './IUserToFriend';
export * from './IProductInList';